title: You Got This
email: yougotthis@underland.xyz
description: >-
  An affordable one-stream conference for junior developers and designers on skills needed for a happy, healthy work life.
url: 'https://yougotthis.io' # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown
include: [_redirects]
